import type { Metadata } from "next";
import { Reveal } from "../../components/Reveal";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";

export const metadata: Metadata = { title:"Events and Fear-of-Flying Seminars | Vienna Flight", description:"Company events, group experiences and fear-of-flying seminars at Vienna Flight." };
const facts = [["220 m²","Total space for your event"],["Several cockpits","Experience Airbus, Boeing and Bell as a team"],["Active pilots","Personal guidance and Q&A sessions"],["Central location","Around three minutes on foot from the U2"]];
export default function EnglishEventsPage() {
  return <main id="top"><Reveal /><SiteHeader dark /><section className="page-hero events-page-hero"><div className="eyebrow"><span /> Fly your event</div><h1>Reach new heights<br /><em>together.</em></h1><p>Extraordinary company and group events, plus a new way to approach fear of flying.</p></section><section className="event-feature"><div className="event-feature-copy reveal"><div className="eyebrow dark"><span /> Groups and companies</div><h2>An event that<br />truly takes off.</h2><p>Whether it is a company celebration, team incentive, anniversary or private event, your guests take the controls while active pilots guide them through the cockpit experience.</p><p>Schedule, duration, catering and content are tailored to your group. We can also arrange a welcome drink, catering and personal certificates.</p><a className="button primary" href="/en/contact">Enquire about an event <span>→</span></a></div><div className="event-feature-image reveal"><img src="/images/events.jpg" alt="Group and company event at Vienna Flight" /><span>Welcome<br />on board</span></div></section><section className="event-facts section"><div className="eyebrow dark reveal"><span /> Facts and possibilities</div><div className="event-fact-grid">{facts.map(([value,label],index) => <article className="reveal" key={value}><span>0{index + 1}</span><h3>{value}</h3><p>{label}</p></article>)}</div></section><section className="anxiety-section"><div className="anxiety-image reveal"><img src="/images/flight-anxiety.jpg" alt="Fear-of-flying seminar in the Airbus A320 simulator" /></div><div className="anxiety-copy reveal"><div className="eyebrow"><span /> Fear-of-flying seminar</div><h2>Take control.<br /><em>Build confidence.</em></h2><p>During this three-day seminar, participants develop personal strategies for more relaxed travel. The programme uses a solution-focused approach and strengthens individual resources.</p><p>The crucial difference is that you take control of our Airbus A320 simulator and experience cockpit routines, teamwork and safety from a new perspective.</p><a className="button light-button" href="/en/contact">Enquire about the seminar <span>→</span></a></div></section><section className="booking-teaser"><div><span className="eyebrow light"><i /> Planned for you</span><h2>Tell us about your event.</h2></div><a className="button light-button" href="/en/contact">Arrange a conversation <span>→</span></a></section><SiteFooter language="en" /></main>;
}
