/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { Reveal } from "../../components/Reveal";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";

export const metadata: Metadata = { title:"Simulator Screening Preparation | Vienna Flight", description:"Professional, airline-specific simulator assessment preparation in an authentic Airbus A320 cockpit." };
const procedures = ["Departure and arrival procedures, SID and STAR","Precision and non-precision approaches","Pitch and power configuration","Holding procedures and holding entry","Instrument cross-check","Airwork, steep turns, climb and descent","Wind correction, go-around and missed approach","Crew resource management"];
export default function EnglishScreeningPage() {
  return <main id="top"><Reveal /><SiteHeader dark /><section className="page-hero screening-page-hero"><div className="eyebrow"><span /> For aspiring pilots</div><h1>Ready for your<br /><em>simulator screening.</em></h1><p>Airline-specific preparation with experienced airline pilots in an authentic Airbus A320 simulator.</p></section><section className="professional-intro"><div className="professional-image reveal"><img src="/images/screening.jpg" alt="Simulator assessment preparation at Vienna Flight" /><span>Assessment<br />Preparation</span></div><div className="professional-copy reveal"><div className="eyebrow dark"><span /> Professionally prepared</div><h2>Do not leave your<br />pilot career<br />to chance.</h2><p>Our network of experienced instructors, flight teachers and active commercial pilots supports you in theory and practice. Training is tailored to your target airline's procedures and programme.</p><p>After every session, you receive a structured debriefing with concrete recommendations for your continued preparation.</p><a className="button primary" href="/en/contact">Enquire about training <span>→</span></a></div></section><section className="screening-content section"><div className="section-head reveal"><div><div className="eyebrow dark"><span /> Training content</div><h2>Train with purpose.<br />Perform with confidence.</h2></div><p>The Airbus A320 simulator is fully instrumented. Weather, procedures and a range of failure scenarios can be trained in a controlled setting.</p></div><div className="procedure-grid">{procedures.map((procedure,index) => <div className="procedure reveal" key={procedure}><span>{String(index + 1).padStart(2,"0")}</span><p>{procedure}</p></div>)}</div><div className="screening-note reveal"><strong>Important note</strong><p>Fun Flight vouchers and promotions cannot be used for assessment preparation or professional pilot training.</p></div></section><section className="booking-teaser"><div><span className="eyebrow light"><i /> Your next career step</span><h2>Plan individual training.</h2></div><a className="button light-button" href="/en/contact">Request advice <span>→</span></a></section><SiteFooter language="en" /></main>;
}
