/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { Reveal } from "../../components/Reveal";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";

export const metadata: Metadata = { title:"About Us | Vienna Flight", description:"Meet the team and discover the story behind Vienna's flight simulator centre." };
export default function EnglishAboutPage() {
  return <main id="top"><Reveal /><SiteHeader dark /><section className="page-hero about-page-hero"><div className="eyebrow"><span /> Vienna Flight</div><h1>Driven by a passion<br /><em>for flying.</em></h1><p>Professional guidance, authentic cockpits and a passion for helping people take to the skies with confidence.</p></section><section className="story-section"><div className="story-copy reveal"><div className="eyebrow dark"><span /> Our story</div><h2>Flying should be more<br />than a dream.</h2><p>Vienna Flight began with one simple idea: the fascination of a real cockpit should be accessible to everyone. Today our experienced instructors guide guests from their first takeoff to demanding training sessions.</p><p>What drives us is the moment when concentration turns into a smile. We combine technology, hospitality and expert guidance to create an experience of the highest standard.</p></div><div className="story-image reveal"><img src="/images/cockpit-hero.jpg" alt="Airbus cockpit at Vienna Flight" /></div></section><section className="values section"><div className="section-head reveal"><div><div className="eyebrow dark"><span /> What we stand for</div><h2>Precision meets<br />enthusiasm.</h2></div></div><div className="value-grid"><article><span>01</span><h3>Authenticity</h3><p>Original components and realistic procedures make the difference.</p></article><article><span>02</span><h3>Personal attention</h3><p>Every flight is adapted to the guest's experience, preferences and pace.</p></article><article><span>03</span><h3>Professionalism</h3><p>Experienced instructors provide clear guidance and a safe experience.</p></article></div></section><SiteFooter language="en" /></main>;
}
