<<<<<<< ours
app = "vf-web"
primary_region = "vie"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "15s"
    interval = "30s"
    method = "GET"
    path = "/preview-login"
    timeout = "5s"
=======
# fly.toml app configuration file generated for vf-web on 2026-09-13T17:59:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vf-web'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
>>>>>>> theirs
