"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AdminNavigation } from "../../../components/AdminNavigation";
import { simulators } from "../../../lib/site-data";
import type { Instructor } from "../../../lib/instructors-db";

const times=["09:30","11:00","12:30","14:00","15:30","17:00","18:30"];
const minutes=(value:string)=>{const [hours,mins]=value.split(":").map(Number);return hours*60+mins;};

export default function InternalBookingPage(){
  const [instructors,setInstructors]=useState<Instructor[]>([]),[simulator,setSimulator]=useState(simulators[0].name),[duration,setDuration]=useState(60),[date,setDate]=useState(""),[minimumDate,setMinimumDate]=useState(""),[time,setTime]=useState("14:00"),[saving,setSaving]=useState(false),[error,setError]=useState(""),[created,setCreated]=useState("");
  useEffect(()=>{const viennaToday=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Vienna",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());setDate(viennaToday);setMinimumDate(viennaToday);Promise.all([fetch("/api/admin/session",{credentials:"same-origin"}),fetch("/api/admin/instructors",{credentials:"same-origin"})]).then(async([sessionResponse,instructorResponse])=>{const session=await sessionResponse.json(),data=await instructorResponse.json();if(!sessionResponse.ok||session.user?.role!=="editor"||instructorResponse.status===401){window.location.replace(session.user?.role==="instructor"?"/admin/availability":"/admin");return;}if(instructorResponse.ok)setInstructors(data.instructors??[]);else setError(data.error??"Instructoren konnten nicht geladen werden.");}).catch(()=>setError("Dashboard-Daten konnten nicht geladen werden."));},[]);
  useEffect(()=>{if(!simulators.find(item=>item.name===simulator)?.prices[duration])setDuration(60);},[simulator,duration]);
  const availableInstructors=useMemo(()=>instructors.filter(instructor=>{if(!instructor.active||!(instructor.capabilities??[]).includes(simulator))return false;const range=(instructor.availabilityRanges??[]).find(item=>item.available_date===date);return !!range&&minutes(time)>=minutes(range.available_from)&&minutes(time)+duration<=minutes(range.available_until)+1;}),[instructors,simulator,date,time,duration]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;setSaving(true);setError("");setCreated("");const form=new FormData(formElement),instructorSelection=String(form.get("instructorSelection")??"auto");try{const response=await fetch("/api/admin/bookings",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify({simulator,duration,date,time,name:form.get("name"),email:form.get("email"),phone:form.get("phone"),remark:form.get("remark"),internalNotes:form.get("internalNotes"),voucherCode:form.get("voucherCode"),language:form.get("language"),status:form.get("status"),instructorMode:instructorSelection==="none"?"none":"auto",instructorId:instructorSelection.startsWith("id:")?Number(instructorSelection.slice(3)):null,gift:form.get("gift")==="on"})}),data=await response.json();if(response.status===401){window.location.replace("/admin");return;}if(response.ok){setCreated(data.reference);formElement.reset();}else setError(data.error??"Buchung konnte nicht angelegt werden.");}catch{setError("Buchung konnte nicht übertragen werden.");}finally{setSaving(false);}}
  return <main className="admin-shell"><AdminNavigation active="bookings"/><section className="admin-content management-content"><header className="admin-topbar"><div><span className="micro-label">Interne Buchung</span><h1>Neue Buchung</h1><p>Termin und alle operativen Angaben direkt anlegen.</p></div></header>{error&&<div className="admin-error" role="alert">{error}</div>}{created&&<div className="admin-notice" role="status">Buchung {created} wurde angelegt. <a href="/admin">Zur Buchungsübersicht</a></div>}<form className="internal-booking-form" onSubmit={submit}>
    <fieldset><legend>Flug</legend><label>Simulator<select value={simulator} onChange={event=>setSimulator(event.target.value)}>{simulators.map(item=><option key={item.name}>{item.name}</option>)}</select></label><label>Dauer<select value={duration} onChange={event=>setDuration(Number(event.target.value))}>{[30,60,90,120].filter(value=>simulators.find(item=>item.name===simulator)?.prices[value]).map(value=><option value={value} key={value}>{value} Minuten</option>)}</select></label><label>Datum<input type="date" value={date} min={minimumDate} onChange={event=>setDate(event.target.value)} required/></label><label>Startzeit<select value={time} onChange={event=>setTime(event.target.value)}>{times.map(value=><option key={value}>{value}</option>)}</select></label><label>Sprache<select name="language"><option value="de">Deutsch</option><option value="en">Englisch</option></select></label><label>Status<select name="status"><option value="pending">Offene Anfrage</option><option value="confirmed">Bestätigt</option></select></label></fieldset>
    <fieldset><legend>Kunde</legend><label>Name<input name="name" required maxLength={160}/></label><label>E-Mail<input name="email" type="email" required maxLength={254}/></label><label>Telefon<input name="phone" type="tel" required maxLength={80}/></label><label>Gutscheincode<input name="voucherCode" autoCapitalize="characters"/></label><label className="internal-booking-wide">Bemerkung des Kunden<textarea name="remark" rows={4} maxLength={2000}/></label><label className="internal-checkbox"><input name="gift" type="checkbox"/> Als Geschenkgutschein führen</label></fieldset>
    <fieldset><legend>Interne Verwaltung</legend><label>Instructor<select name="instructorSelection"><option value="auto">Tageszuordnung übernehmen</option><option value="none">Nicht zuordnen</option>{availableInstructors.map(item=><option value={`id:${item.id}`} key={item.id}>{item.name}</option>)}</select><small>{availableInstructors.length} Instructor(en) decken den vollständigen Termin ab.</small></label><label className="internal-booking-wide">Interne Anmerkung<textarea name="internalNotes" rows={5} maxLength={4000}/></label></fieldset>
    <footer><a href="/admin">Abbrechen</a><button className="button primary" disabled={saving} type="submit">{saving?"Buchung wird angelegt ...":"Buchung anlegen"}</button></footer>
  </form></section></main>;
}
