/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { LegalPage } from "../../components/LegalPage";

export const metadata: Metadata = { title: "Privacy | Vienna Flight", description: "Vienna Flight privacy policy." };

export default function PrivacyPage() {
  return <LegalPage language="en" eyebrow="Your data" title="Privacy" intro="Information about the collection, use and processing of personal data.">
    <aside className="legal-language-note"><strong>Translation notice</strong><p>This English version is provided for convenience. The German privacy policy is authoritative.</p></aside>
    <section><h2>1. Material and territorial scope</h2><p>This policy describes how ViennaFlight - Flightsimulation &amp; Flighttraining OG, referred to as ViennaFlight, collects, uses and processes your personal data and complies with its legal obligations. Protecting your data and privacy rights is important to us.</p><p>The policy applies to personal data concerning visitors to www.viennaflight.at, customers and other people with whom we make contact and whose data may be stored. For applicable data protection laws, including Regulation (EU) 2016/679, the GDPR, the controller is:</p><address><strong>ViennaFlight</strong><br />Flightsimulation &amp; Flighttraining OG<br />Schönngasse 15-17/2/Top 3<br />1020 Vienna<br />Austria</address><p>Data protection requirements may change, and this policy will be updated accordingly.</p></section>
    <section><h2>2. Lawfulness of processing</h2><p>Personal data is processed where necessary to perform a contract with the data subject, take pre-contractual measures at the person's request, comply with legal obligations, or protect the rights of the data subject.</p></section>
    <section><h2>3. Types of processing</h2><h3>3.1 Customer data</h3><p>To maintain customer contact and orderly payment processing, data submitted through our forms may be stored, including company details, first and last name, date of birth, address, telephone number, email address and IP address.</p><h3>3.2 Website visitors</h3><p>For internal statistical purposes, we may record the visitor's IP address, requested file, date and time, transferred data volume, browser type, country and requesting URL.</p><h3>3.3 Data received from controllers</h3><p>We may receive and process personal data from controllers, mainly event companies. The controller is responsible for consent and accuracy. This data may include name, email address, telephone number and address. You retain rights to information and deletion.</p></section>
    <section><h2>4. Types of data</h2><h3>4.1 Personal data</h3><p>Until consent is withdrawn, ViennaFlight may process company details, name, address, telephone number and email address. Data is passed to third parties only for contract performance, particularly order details required by suppliers for billing, or where you have consented.</p><h3>4.1.1 Children's data</h3><p>ViennaFlight does not generally store or process children's personal data. Where such data is available, it is processed only with the consent of the legal guardian. A minimum age of 16 applies to the proper booking of our services.</p><h3>4.1.2 Disclosure to third parties</h3><p>To provide our range of services, personal data may be passed to processing partners. Detailed information is available through your right of access.</p><h3>4.2 Sensitive data</h3><p>ViennaFlight does not store or process sensitive data.</p></section>
    <section><h2>5. Right of access and rectification</h2><p>You have the right to obtain information about your personal data stored by us. ViennaFlight may provide the requested information within one month where data is available. If justified doubts exist, proof of identity may be required. Incorrect personal data may be rectified within one month.</p></section>
    <section><h2>6. Right to erasure</h2><p>You have the right to request deletion of personal data stored by ViennaFlight. ViennaFlight may complete deletion within one month. Where data is held by processing parties, the period may be extended by two months. Internal company policies apply for the duration of storage.</p></section>
    <section><h2>7. Withdrawal</h2><p>Information concerning the right to withdraw is available on our website under withdrawal, unless stated otherwise.</p></section>
    <section><h2>8. Security</h2><p>The website www.viennaflight.at is protected by a verified SSL certificate. System backups are regularly performed by our IT service provider.</p></section>
    <section><h2>9. Cookies</h2><p>A cookie is information stored on your computer that records navigation on a website. It can provide tailored options based on a previous visit. Cookies may also be used for traffic analysis, advertising and marketing.</p></section>
    <section><h2>10. Google Analytics</h2><p>This website uses Google Analytics, a web analytics service from Google Ireland Limited. Google Analytics uses cookies to analyse website use. Information generated by a cookie, including an abbreviated IP address, is generally transmitted to and stored on a Google server.</p><p>The _anonymizeIp() extension is used to abbreviate the IP address and prevent direct personal identification. Only in exceptional cases is the full IP address sent to a server in the United States and abbreviated there. The transmitted IP address is not combined with other Google data.</p><p>Google may use this information on behalf of the website operator to evaluate website use, compile reports and provide related services. Collection can be prevented through this website's cookie settings. Google's opt-out plug-in is available at <a href="https://tools.google.com/dlpage/gaoptout">tools.google.com/dlpage/gaoptout</a>. Further information is available in <a href="https://policies.google.com/privacy">Google's privacy policy</a>.</p></section>
    <section><h2>Controller and supervisory authority</h2><address><strong>ViennaFlight</strong><br />Flightsimulation &amp; Flighttraining OG<br />Schönngasse 15-17/2/Top 3<br />1020 Vienna<br />Austria</address><h3>Local supervisory authority</h3><address>Austrian Data Protection Authority<br />Wickenburggasse 8<br />1080 Vienna<br />Telephone: <a href="tel:+431521520">+43 1 52 152-0</a></address><h3>Privacy policy author</h3><p>innovative desire e.U.<br />Prof. Ing. Yun Xiang, certified data protection expert</p></section>
  </LegalPage>;
}
