import type { Metadata } from "next";
import { LegalPage } from "../components/LegalPage";

export const metadata: Metadata = { title: "Impressum | Vienna Flight", description: "Impressum und Anbieterinformationen von Vienna Flight." };

export default function ImpressumPage() {
  return <LegalPage eyebrow="Rechtliche Informationen" title="Impressum" intro="Medieninhaber und verantwortlich für den Inhalt dieser Website.">
    <section><h2>Medieninhaber und verantwortlich für den Inhalt</h2><address><strong>Vienna FLIGHT</strong><br />Flightsimulation &amp; Flighttraining OG<br />Geschäftsführer Gerhard Lück<br />Schönngasse 15-17/2/Top 3<br />A-1020 Wien</address><p>T: <a href="tel:+4319072711">+43/1/907 27 11</a><br />E: <a href="mailto:office@viennaflight.at">office@viennaflight.at</a><br />Web: www.viennaflight.at</p></section>
    <section><h2>Unternehmensangaben</h2><p>Registriert unter der Firmenbuchnummer FN 370636 d beim Handelsgericht Wien<br />UID-Nr.: ATU66896139<br />Steuernummer: 480/1739, Finanzamt Wien<br />Mitglied der Wirtschaftskammer Österreich<br />Behörde gem. ECG (E-Commerce Gesetz): Magistratisches Bezirksamt für den 2. Bezirk</p><p>ViennaFlight ist eine eingetragene Marke und wird unter der Nummer 260999 beim Österreichischen Patent- und Markenamt geführt. Die Nutzung der Marke ist nur mit schriftlicher Genehmigung durch ViennaFlight, Flightsimulation &amp; Flighttraining OG erlaubt.</p></section>
    <section><h2>Urheberrecht</h2><p>© 2011-2024 ViennaFlight, Flightsimulation &amp; Flighttraining OG. Alle Rechte vorbehalten.</p><p>Bilder auf dieser Website: © ViennaFlight, www.foto-julius.at, Jeppesen Inc., Fotolia.de, nun Adobe Stock, und Shutterstock.de.</p><p>Die Übernahme von Bildern und Texten, auch auszugsweise, ist nur mit schriftlicher Genehmigung durch ViennaFlight, Flightsimulation &amp; Flighttraining OG gestattet.</p><p>Website und grafisches Design: © 2011-2024 ViennaFlight.</p><p>Wir bedanken uns für die technische und werbetechnische Unterstützung von innovative desire e.U. Ihre Daten werden sorgfältig gepflegt und entsprechen der DSGVO.</p></section>
    <section><h2>Haftungsausschluss</h2><h3>1. Inhalt des Onlineangebotes</h3><p>Der Autor übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen den Autor, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen beziehungsweise durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens des Autors kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt.</p><p>Alle Angebote sind freibleibend und unverbindlich. Der Autor behält es sich ausdrücklich vor, Teile der Seite oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.</p><p>Aus Gründen der besseren Lesbarkeit wird auf die gleichzeitige Verwendung männlicher und weiblicher Sprachformen verzichtet. Sämtliche Personenbezeichnungen gelten gleichwohl für beide Geschlechter.</p>
    <h3>2. Verweise und Links</h3><p>Bei direkten oder indirekten Verweisen auf fremde Webseiten, die außerhalb des Verantwortungsbereiches des Autors liegen, würde eine Haftungsverpflichtung ausschließlich in dem Fall in Kraft treten, in dem der Autor von den Inhalten Kenntnis hat und es ihm technisch möglich und zumutbar wäre, die Nutzung im Falle rechtswidriger Inhalte zu verhindern.</p><p>Der Autor erklärt ausdrücklich, dass zum Zeitpunkt der Linksetzung keine illegalen Inhalte auf den verlinkten Seiten erkennbar waren. Auf die aktuelle und zukünftige Gestaltung, die Inhalte oder die Urheberschaft der verlinkten Seiten hat der Autor keinerlei Einfluss. Diese Feststellung gilt für alle innerhalb des eigenen Internetangebotes gesetzten Links und Verweise sowie für Fremdeinträge in Bereichen, auf deren Inhalt externe Schreibzugriffe möglich sind.</p><p>Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere für Schäden, die aus der Nutzung oder Nichtnutzung solcher Informationen entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde.</p>
    <h3>3. Urheber- und Kennzeichnungsrecht</h3><p>Der Autor ist bestrebt, die Urheberrechte der verwendeten Bilder, Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, eigene Inhalte zu nutzen oder auf lizenzfreie Inhalte zurückzugreifen. Alle innerhalb des Internetangebotes genannten und gegebenenfalls durch Dritte geschützten Marken- und Warenzeichen unterliegen den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der eingetragenen Eigentümer.</p><p>Das Copyright für veröffentlichte, vom Autor selbst erstellte Objekte bleibt allein beim Autor der Seiten. Eine Vervielfältigung oder Verwendung solcher Inhalte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung des Autors nicht gestattet.</p>
    <h3>4. Rechtswirksamkeit dieses Haftungsausschlusses</h3><p>Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt.</p></section>
    <section><h2>Markenhinweise</h2><p>Unser Airbus A320 Cockpitsimulator besteht aus originalen Airbusteilen, die aus einem echten Flugzeug stammen, jedoch nicht durch Airbus unterstützt werden. Airbus und A320 sind registrierte Marken der Airbus S.A.S./Airbus Deutschland GmbH.</p><p>Boeing und Boeing 787 sind registrierte Marken der Boeing Company. Bell und Bell 206 Jet Ranger sind registrierte Marken der Bell Helicopter Textron Inc. Eurofighter und Eurofighter Typhoon sind registrierte Marken der Eurofighter Jagdflugzeug GmbH.</p></section>
  </LegalPage>;
}
