/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { LegalPage } from "../../components/LegalPage";

export const metadata: Metadata = { title: "Legal Notice | Vienna Flight", description: "Legal notice and provider information for Vienna Flight." };

export default function LegalNoticePage() {
  return <LegalPage language="en" eyebrow="Legal information" title="Legal notice" intro="Website owner and party responsible for the content.">
    <aside className="legal-language-note"><strong>Translation notice</strong><p>This English version is provided for convenience. The German legal notice is authoritative.</p></aside>
    <section><h2>Website owner and responsible party</h2><address><strong>Vienna FLIGHT</strong><br />Flightsimulation &amp; Flighttraining OG<br />Managing Director: Gerhard Lück<br />Schönngasse 15-17/2/Top 3<br />A-1020 Vienna<br />Austria</address><p>Telephone: <a href="tel:+4319072711">+43/1/907 27 11</a><br />Email: <a href="mailto:office@viennaflight.at">office@viennaflight.at</a><br />Website: www.viennaflight.at</p></section>
    <section><h2>Company information</h2><p>Registered under company number FN 370636 d at the Commercial Court of Vienna<br />VAT number: ATU66896139<br />Tax number: 480/1739, Vienna Tax Office<br />Member of the Austrian Federal Economic Chamber<br />Authority pursuant to the Austrian E-Commerce Act: Municipal District Office for Vienna's 2nd district</p><p>ViennaFlight is a registered trademark, number 260999 at the Austrian Patent Office. Use of the trademark requires written permission from ViennaFlight, Flightsimulation &amp; Flighttraining OG.</p></section>
    <section><h2>Copyright</h2><p>© 2011-2024 ViennaFlight, Flightsimulation &amp; Flighttraining OG. All rights reserved.</p><p>Images on this website: © ViennaFlight, www.foto-julius.at, Jeppesen Inc., Fotolia.de, now Adobe Stock, and Shutterstock.de.</p><p>Images and texts, including extracts, may only be reproduced with written permission from ViennaFlight, Flightsimulation &amp; Flighttraining OG.</p><p>Website and graphic design: © 2011-2024 ViennaFlight.</p></section>
    <section><h2>Disclaimer</h2><h3>1. Online content</h3><p>The author makes no guarantee regarding the timeliness, correctness, completeness or quality of the information provided. Liability claims relating to material or immaterial damage caused by the use or non-use of the information, or by the use of incorrect or incomplete information, are excluded unless intentional or grossly negligent fault can be demonstrated.</p><p>All offers are non-binding. The author reserves the right to change, supplement or delete parts of the website or the entire offering, or to suspend publication temporarily or permanently without separate notice.</p><h3>2. References and links</h3><p>Liability for direct or indirect references to external websites outside the author's area of responsibility would apply only if the author knew of unlawful content and it was technically possible and reasonable to prevent its use. At the time links were created, no unlawful content was identifiable. The provider of the linked page is solely responsible for illegal, incorrect or incomplete content and for damage resulting from its use.</p><h3>3. Copyright and trademark law</h3><p>The author endeavours to respect the copyrights of all images, graphics, audio documents, video sequences and texts used. Third-party trademarks remain subject to applicable trademark law and the ownership rights of their registered owners. Copyright in content created by the author remains with the author. Reproduction in electronic or printed publications requires express consent.</p><h3>4. Legal validity</h3><p>This disclaimer forms part of the website from which this page was linked. If individual parts or wording no longer fully comply with applicable law, the content and validity of the remaining parts remain unaffected.</p></section>
  </LegalPage>;
}
