"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { AdminNavigation } from "../../components/AdminNavigation";
import type { AdminIdentity } from "../../lib/admin-auth";
import type { Instructor } from "../../lib/instructors-db";
import { simulators } from "../../lib/site-data";
type UserRecord={id:number;username:string;display_name:string;email:string|null;active:number};
type Member={kind:"editor";data:UserRecord}|{kind:"instructor";data:Instructor};

export default function UsersAdminPage(){
 const router=useRouter(),[checking,setChecking]=useState(true),[identity,setIdentity]=useState<AdminIdentity|null>(null),[users,setUsers]=useState<UserRecord[]>([]),[instructors,setInstructors]=useState<Instructor[]>([]),[defaultUser,setDefaultUser]=useState("admin"),[createOpen,setCreateOpen]=useState(false),[userClass,setUserClass]=useState<"editor"|"instructor">("editor"),[menu,setMenu]=useState(""),[editing,setEditing]=useState<Member|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const [ur,ir]=await Promise.all([fetch("/api/admin/users"),fetch("/api/admin/instructors")]);if(ur.status===401){router.replace("/admin");return}const ud=await ur.json(),id=await ir.json();if(ur.ok){setUsers(ud.users);setDefaultUser(ud.defaultUser)}else setError(ud.error);if(ir.ok)setInstructors(id.instructors)},[router]);
 useEffect(()=>{fetch("/api/admin/session").then(r=>r.json()).then(data=>{if(!data.authenticated){router.replace("/admin");return}setIdentity(data.user);void load()}).catch(()=>setError("Die Sitzung konnte nicht geprüft werden.")).finally(()=>setChecking(false))},[load,router]);
 async function createStaff(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const formElement=event.currentTarget,form=new FormData(formElement),username=String(form.get("username")??""),email=String(form.get("email")??""),password=String(form.get("password")??""),editor=userClass==="editor",response=await fetch(editor?"/api/admin/users":"/api/admin/instructors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editor?{username,displayName:username,email,password}:{action:"create",name:username,email,username,password})}),data=await response.json();if(response.ok){formElement.reset();setCreateOpen(false);setNotice(data.invitation?.sent?`Konto erstellt. Die Einladungs-E-Mail wurde an ${email} gesendet.`:(data.invitation?.error??"Konto wurde erstellt."));await load()}else setError(data.error);setSaving(false)}
 async function saveMember(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;setSaving(true);setError("");const form=new FormData(event.currentTarget),name=String(form.get("name")??""),email=String(form.get("email")??""),password=String(form.get("temporaryPassword")??"");if(editing.kind==="editor"){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing.data.id,displayName:name,email,active:Boolean(editing.data.active),password})});if(!r.ok)setError((await r.json()).error);else{setEditing(null);await load()}}else{const capabilities=form.getAll("capabilities").map(String),profile=await fetch("/api/admin/instructors",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing.data.id,action:"profile",name,email,password})});if(profile.ok){await fetch("/api/admin/instructors",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing.data.id,action:"capabilities",capabilities})});setEditing(null);await load()}else setError((await profile.json()).error)}setSaving(false)}
 async function toggle(member:Member){const active=member.data.active!==1;if(member.kind==="editor")await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:member.data.id,displayName:member.data.display_name,email:member.data.email,active,password:""})});else await fetch("/api/admin/instructors",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:member.data.id,active})});setMenu("");await load()}
 async function remove(member:Member){if(!window.confirm("Diesen Benutzer dauerhaft löschen? Bestehende Buchungen bleiben erhalten."))return;const url=member.kind==="editor"?`/api/admin/users?id=${member.data.id}`:`/api/admin/instructors?instructorId=${member.data.id}`,response=await fetch(url,{method:"DELETE"});if(response.ok){setMenu("");setNotice("Benutzer wurde gelöscht.");await load()}else setError((await response.json()).error)}
 async function sendReset(member:Member){const username=member.data.username;if(!username)return;const r=await fetch("/api/admin/password-reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"send",username})}),d=await r.json();if(r.ok)setNotice(`Reset-Link wurde an ${member.data.email} gesendet.`);else setError(d.error);setMenu("")}
 if(checking)return <main className="admin-loading"><p>Sitzung wird geprüft</p></main>;if(!identity)return null;const members:Member[]=[...users.map(data=>({kind:"editor" as const,data})),...instructors.map(data=>({kind:"instructor" as const,data}))];
 return <main className="admin-shell"><AdminNavigation active="users"/><section className="admin-content management-content"><header className="admin-topbar users-topbar"><div><span className="micro-label">Team und Zugriff</span><h1>Mitglieder</h1><p>Editoren und Instructoren zentral verwalten.</p></div><button className="add-member-button" type="button" onClick={()=>setCreateOpen(true)} aria-label="Benutzer hinzufügen">+</button></header>{error&&<div className="admin-error" role="alert">{error}</div>}{notice&&<div className="admin-notice" role="status">{notice}</div>}
 <section className="team-directory"><header><div><span className="micro-label">Team</span><h2>{members.length+1} Mitglieder</h2></div></header><article className="member-row"><div className="user-avatar">A</div><div><h3>Administrator <span>Eigentümer</span></h3><p>@{defaultUser}</p></div><span className="user-state active">Aktiv</span></article>{members.map(member=>{const instructor=member.kind==="instructor",name=instructor?member.data.name:member.data.display_name,key=`${member.kind}-${member.data.id}`;return <article className={`member-row${member.data.active?"":" inactive"}`} key={key}><div className="user-avatar">{name[0]?.toUpperCase()}</div><div className="member-identity"><h3>{name} <span>{instructor?"Instructor":"Editor"}</span></h3><p>@{member.data.username} · {member.data.email}</p>{instructor&&<small>{member.data.capabilities?.length?member.data.capabilities.join(" · "):"Keine Simulator-Berechtigung"}</small>}</div><span className={`user-state ${member.data.active?"active":"disabled"}`}>{member.data.active?"Aktiv":"Deaktiviert"}</span><div className="member-menu-wrap"><button className="member-menu-button" type="button" aria-label={`${name} verwalten`} aria-expanded={menu===key} onClick={()=>setMenu(menu===key?"":key)}>•••</button>{menu===key&&<div className="member-menu" role="menu"><button onClick={()=>{setEditing(member);setMenu("")}}>Bearbeiten</button><button onClick={()=>void toggle(member)}>{member.data.active?"Deaktivieren":"Aktivieren"}</button><button onClick={()=>void sendReset(member)}>Passwort zurücksetzen</button><button className="danger" onClick={()=>void remove(member)}>Löschen</button></div>}</div></article>})}</section>
 {createOpen&&<div className="member-modal-backdrop"><form className="member-modal" onSubmit={createStaff}><header><div><span className="micro-label">Neues Teammitglied</span><h2>Benutzer hinzufügen</h2></div><button type="button" onClick={()=>setCreateOpen(false)} aria-label="Schließen">×</button></header><label>Benutzerklasse<select value={userClass} onChange={event=>setUserClass(event.target.value as "editor"|"instructor")}><option value="editor">Editor</option><option value="instructor">Instructor</option></select></label><label>Benutzername<input name="username" required minLength={3} pattern="[a-zA-Z0-9._-]+"/></label><label>E-Mail<input name="email" type="email" required/></label><label>Initiales Passwort<input name="password" type="password" required minLength={12}/></label><p>Der Benutzer erhält eine E-Mail mit Benutzername und einem sicheren Link, um ein persönliches Passwort festzulegen.</p><button className="button primary" disabled={saving}>Benutzer anlegen</button></form></div>}
 {editing&&<div className="member-modal-backdrop"><form className="member-modal" onSubmit={saveMember}><header><div><span className="micro-label">Mitglied bearbeiten</span><h2>{editing.kind==="instructor"?editing.data.name:editing.data.display_name}</h2></div><button type="button" onClick={()=>setEditing(null)} aria-label="Schließen">×</button></header><label>Name<input name="name" defaultValue={editing.kind==="instructor"?editing.data.name:editing.data.display_name} required/></label><label>E-Mail<input name="email" type="email" defaultValue={editing.data.email??""} required/></label><label>Neues temporäres Passwort<input name="temporaryPassword" type="password" minLength={12} placeholder="Leer lassen, um es nicht zu ändern" autoComplete="new-password"/></label>{editing.kind==="instructor"&&<fieldset className="capability-picker"><legend>Simulator-Berechtigungen</legend>{simulators.map(simulator=><label key={simulator.name}><input name="capabilities" type="checkbox" value={simulator.name} defaultChecked={(editing.data.capabilities??[]).includes(simulator.name)}/>{simulator.name}</label>)}</fieldset>}<button className="button primary" disabled={saving}>Änderungen speichern</button></form></div>}</section></main>;
}
