import { Reveal } from "../components/Reveal";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";
import { NewsSection } from "../components/NewsSection";
import { simulatorsEnglish } from "../lib/site-data";

export default function EnglishHome() {
  return <main><Reveal /><SiteHeader />
    <section className="hero" id="top"><div className="hero-image" aria-hidden="true" /><div className="hero-shade" /><div className="hero-content"><div className="eyebrow"><span /> Flight Simulator Centre Vienna</div><h1>Step in.<br />Take off.<br /><em>Be amazed.</em></h1><p>Four extraordinary simulators. Authentic cockpits. An experience that stays with you long after landing.</p><div className="hero-actions"><a className="button primary" href="/en/booking">Book an experience <span>→</span></a><a className="button ghost" href="/en/simulators">Explore simulators</a></div></div><div className="hero-stats"><div><strong>4</strong><span>Simulators</span></div><div><strong>24,000+</strong><span>Airports</span></div><div><strong>100%</strong><span>Flight feeling</span></div></div></section>
    <NewsSection />
    <section className="simulators section"><div className="section-head reveal"><div><div className="eyebrow dark"><span /> Our fleet</div><h2>Which cockpit<br />will you choose?</h2></div><p>From a scheduled flight over Vienna to a high-speed Eurofighter mission. Our experienced instructors make every flight your personal adventure.</p></div><div className="simulator-grid">{simulatorsEnglish.map((sim, index) => <article className="sim-card reveal" key={sim.name} style={{ transitionDelay:index * 80 + "ms" }}><img src={sim.image} alt={`${sim.name} flight simulator`} /><div className="sim-overlay" /><div className="sim-index">0{index + 1}</div><div className="sim-copy"><span>{sim.type}</span><h3>{sim.name}</h3><p>from € {sim.prices[30]}</p></div><a href={`/en/simulators#${sim.slug}`} className="round-link" aria-label={`View ${sim.name}`}>↗</a></article>)}</div><div className="section-action reveal"><a className="text-link" href="/en/simulators">All simulators in detail <span>→</span></a></div></section>
    <section className="experience"><div className="experience-image reveal"><img src="/images/a320.jpg" alt="Airbus A320 simulator cockpit" /><span className="image-tag">Real cockpit<br />Real emotion</span></div><div className="experience-copy reveal"><div className="eyebrow dark"><span /> The experience</div><h2>Be a pilot<br /><em>for a moment.</em></h2><p>Take your seat in an authentic cockpit. Your personal instructor accompanies you from briefing to a perfect landing. No previous experience is required, only a desire to fly.</p><ul><li><b>01</b><span><strong>Personal briefing</strong>Everything you need, clearly explained.</span></li><li><b>02</b><span><strong>Your route, your weather</strong>Depart from any airport you choose.</span></li><li><b>03</b><span><strong>Debriefing and certificate</strong>A memory that lasts.</span></li></ul><a className="text-link" href="/en/experiences">How your flight works <span>→</span></a></div></section>
    <section className="specialist-section section"><div className="section-head reveal"><div><div className="eyebrow dark"><span /> Events and training</div><h2>Take off together.<br />Prepare with purpose.</h2></div><p>From tailored group experiences to professional simulator assessment preparation.</p></div><div className="specialist-grid"><article className="specialist-card reveal"><img src="/images/events.jpg" alt="Group event at Vienna Flight" /><div className="specialist-shade" /><span>Events</span><h3>Fly your event.</h3><p>Company celebrations, group flights and fear-of-flying seminars in an extraordinary venue.</p><a href="/en/events">Discover events <b>→</b></a></article><article className="specialist-card reveal"><img src="/images/screening.jpg" alt="Simulator screening preparation" /><div className="specialist-shade" /><span>Professional training</span><h3>Ready for screening.</h3><p>Airline-specific assessment preparation with experienced airline pilots in the Airbus A320.</p><a href="/en/screening">View training <b>→</b></a></article></div></section>
    <section className="booking-teaser"><div><span className="eyebrow light"><i /> Ready for takeoff?</span><h2>Your cockpit is waiting.</h2><p>See all released appointments in the booking calendar.</p></div><a className="button light-button" href="/en/booking">Open calendar <span>→</span></a></section>
    <section className="testimonials section"><div className="eyebrow dark reveal"><span /> What our guests say</div><div className="quote reveal"><span className="quote-mark">“</span><blockquote>An absolutely brilliant experience. The instructor was fantastic, and I will never forget landing in Innsbruck.</blockquote><div><strong>MAXIMILIAN K.</strong><span>Airbus A320 Fun Flight</span></div></div><div className="rating-row reveal"><div><strong>4.9</strong><span>Google Reviews</span></div><div className="stars">★★★★★</div><p>Recommended by aviation enthusiasts</p></div></section>
    <SiteFooter language="en" />
  </main>;
}
