import { env } from "cloudflare:workers";
import { getAdminSession } from "../../../lib/admin-auth";
import { ensureInstructorDatabase } from "../../../lib/instructors-db";
import { BOOKING_TIMES } from "../../../lib/availability-db";

const bookingTimes=[...BOOKING_TIMES];

export async function GET(request:Request){const session=await getAdminSession(request,env.DB);if(session?.role!=="instructor")return Response.json({error:"Nicht autorisiert."},{status:401});const month=new URL(request.url).searchParams.get("month")??"";if(!/^\d{4}-\d{2}$/.test(month))return Response.json({error:"Ungültiger Monat."},{status:400});const db=await ensureInstructorDatabase(env.DB),instructor=await db.prepare("SELECT id,name FROM instructors WHERE username=? AND active=1").bind(session.username).first<{id:number;name:string}>();if(!instructor)return Response.json({error:"Instructor nicht gefunden."},{status:404});const [availability,ranges,capabilities,appointments,dayAssignments]=await Promise.all([db.prepare("SELECT available_date,available_time FROM instructor_availability WHERE instructor_id=? AND substr(available_date,1,7)=? ORDER BY available_date,available_time").bind(instructor.id,month).all<{available_date:string;available_time:string}>(),db.prepare("SELECT available_date,available_from,available_until FROM instructor_availability_ranges WHERE instructor_id=? AND substr(available_date,1,7)=? ORDER BY available_date").bind(instructor.id,month).all<{available_date:string;available_from:string;available_until:string}>(),db.prepare("SELECT simulator FROM instructor_capabilities WHERE instructor_id=? ORDER BY simulator").bind(instructor.id).all<{simulator:string}>(),db.prepare("SELECT id,reference,simulator,flight_date,flight_time,duration,customer_name,status,instructor_assignment_source FROM bookings WHERE instructor_id=? AND substr(flight_date,1,7)=? AND status IN ('confirmed','completed') ORDER BY flight_date,flight_time").bind(instructor.id,month).all(),db.prepare("SELECT a.id,a.simulator,a.flight_date,r.available_from,r.available_until FROM instructor_day_assignments a JOIN instructor_availability_ranges r ON r.instructor_id=a.instructor_id AND r.available_date=a.flight_date WHERE a.instructor_id=? AND substr(a.flight_date,1,7)=? ORDER BY a.flight_date,a.simulator").bind(instructor.id,month).all()]);return Response.json({instructor,availability:availability.results,ranges:ranges.results,capabilities:capabilities.results.map(item=>item.simulator),appointments:appointments.results,dayAssignments:dayAssignments.results});}

export async function PUT(request:Request){const session=await getAdminSession(request,env.DB);if(session?.role!=="instructor")return Response.json({error:"Nicht autorisiert."},{status:401});const body=await request.json() as Record<string,unknown>,date=String(body.date??""),mode=String(body.mode??""),from=mode==="full_day"?"00:00":String(body.from??""),until=mode==="full_day"?"23:59":String(body.until??""),validTime=(value:string)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(value);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||date<new Date().toISOString().slice(0,10)||!["full_day","custom","unavailable"].includes(mode)||(mode!=="unavailable"&&(!validTime(from)||!validTime(until)||from>=until)))return Response.json({error:"Ungültige Verfügbarkeit."},{status:400});const db=await ensureInstructorDatabase(env.DB),instructor=await db.prepare("SELECT id FROM instructors WHERE username=? AND active=1").bind(session.username).first<{id:number}>();if(!instructor)return Response.json({error:"Instructor nicht gefunden."},{status:404});const selected=mode==="unavailable"?[]:bookingTimes.filter(time=>time>=from&&time<=until),statements=[db.prepare("DELETE FROM instructor_availability WHERE instructor_id=? AND available_date=?").bind(instructor.id,date),db.prepare("DELETE FROM instructor_availability_ranges WHERE instructor_id=? AND available_date=?").bind(instructor.id,date),...selected.map(time=>db.prepare("INSERT INTO instructor_availability (instructor_id,available_date,available_time) VALUES (?,?,?)").bind(instructor.id,date,time))];if(mode!=="unavailable")statements.push(db.prepare("INSERT INTO instructor_availability_ranges (instructor_id,available_date,available_from,available_until) VALUES (?,?,?,?)").bind(instructor.id,date,from,until));await db.batch(statements);return Response.json({updated:true,mode,times:selected,range:mode==="unavailable"?null:{available_date:date,available_from:from,available_until:until}});}
