import { env } from "cloudflare:workers";
import { getAdminSession } from "../../../lib/admin-auth";
import { ensureInstructorDatabase } from "../../../lib/instructors-db";

const bookingTimes=["09:30","11:00","12:30","14:00","15:30","17:00","18:30"];

export async function GET(request:Request){const session=await getAdminSession(request,env.DB);if(session?.role!=="instructor")return Response.json({error:"Nicht autorisiert."},{status:401});const month=new URL(request.url).searchParams.get("month")??"";if(!/^\d{4}-\d{2}$/.test(month))return Response.json({error:"Ungültiger Monat."},{status:400});const db=await ensureInstructorDatabase(env.DB),instructor=await db.prepare("SELECT id,name FROM instructors WHERE username=? AND active=1").bind(session.username).first<{id:number;name:string}>();if(!instructor)return Response.json({error:"Instructor nicht gefunden."},{status:404});const [availability,ranges,capabilities]=await Promise.all([db.prepare("SELECT available_date,available_time FROM instructor_availability WHERE instructor_id=? AND substr(available_date,1,7)=? ORDER BY available_date,available_time").bind(instructor.id,month).all<{available_date:string;available_time:string}>(),db.prepare("SELECT available_date,available_from,available_until FROM instructor_availability_ranges WHERE instructor_id=? AND substr(available_date,1,7)=? ORDER BY available_date").bind(instructor.id,month).all<{available_date:string;available_from:string;available_until:string}>(),db.prepare("SELECT simulator FROM instructor_capabilities WHERE instructor_id=? ORDER BY simulator").bind(instructor.id).all<{simulator:string}>()]);return Response.json({instructor,availability:availability.results,ranges:ranges.results,capabilities:capabilities.results.map(item=>item.simulator)});}

export async function PUT(request:Request){const session=await getAdminSession(request,env.DB);if(session?.role!=="instructor")return Response.json({error:"Nicht autorisiert."},{status:401});const body=await request.json() as Record<string,unknown>,date=String(body.date??""),mode=String(body.mode??""),from=mode==="full_day"?"00:00":String(body.from??""),until=mode==="full_day"?"23:59":String(body.until??""),validTime=(value:string)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(value);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||date<new Date().toISOString().slice(0,10)||!["full_day","custom","unavailable"].includes(mode)||(mode!=="unavailable"&&(!validTime(from)||!validTime(until)||from>=until)))return Response.json({error:"Ungültige Verfügbarkeit."},{status:400});const db=await ensureInstructorDatabase(env.DB),instructor=await db.prepare("SELECT id FROM instructors WHERE username=? AND active=1").bind(session.username).first<{id:number}>();if(!instructor)return Response.json({error:"Instructor nicht gefunden."},{status:404});const selected=mode==="unavailable"?[]:bookingTimes.filter(time=>time>=from&&time<=until),statements=[db.prepare("DELETE FROM instructor_availability WHERE instructor_id=? AND available_date=?").bind(instructor.id,date),db.prepare("DELETE FROM instructor_availability_ranges WHERE instructor_id=? AND available_date=?").bind(instructor.id,date),...selected.map(time=>db.prepare("INSERT INTO instructor_availability (instructor_id,available_date,available_time) VALUES (?,?,?)").bind(instructor.id,date,time))];if(mode!=="unavailable")statements.push(db.prepare("INSERT INTO instructor_availability_ranges (instructor_id,available_date,available_from,available_until) VALUES (?,?,?,?)").bind(instructor.id,date,from,until));await db.batch(statements);return Response.json({updated:true,mode,times:selected,range:mode==="unavailable"?null:{available_date:date,available_from:from,available_until:until}});}
