import type { Metadata } from "next";
import { LegalPage } from "../components/LegalPage";

export const metadata: Metadata = { title: "Datenschutz | Vienna Flight", description: "Datenschutzerklärung von Vienna Flight." };

export default function DatenschutzPage() {
  return <LegalPage eyebrow="Ihre Daten" title="Datenschutz" intro="Informationen zur Erfassung, Nutzung und Verarbeitung personenbezogener Daten.">
    <section><h2>1. Sachlicher und räumlicher Anwendungsbereich</h2><p>In dieser Datenschutzrichtlinie wird beschrieben, wie wir, ViennaFlight - Flightsimulation &amp; Flighttraining OG, in Folge ViennaFlight genannt, Ihre personenbezogenen Daten erfassen, nutzen und verarbeiten und wie wir dabei unseren gesetzlichen Verpflichtungen Ihnen gegenüber nachkommen. Der Schutz Ihrer Daten ist uns wichtig und wir haben es uns zur Aufgabe gemacht, Ihre Datenschutzrechte zu schützen und zu wahren.</p><p>Diese Datenschutzrichtlinie gilt für die personenbezogenen Daten der Besucher unserer Webseite www.viennaflight.at, unserer Kunden und weitere Personen, mit denen wir Kontakt aufnehmen und deren Daten gespeichert werden könnten.</p><p>Zum Zwecke der geltenden Datenschutzgesetze, darunter unter anderem die Datenschutz-Grundverordnung, Verordnung (EU) 2016/679, in Folge DSGVO genannt, werden die personenbezogenen Daten verarbeitet von:</p><address><strong>ViennaFlight</strong><br />Flightsimulation &amp; Flighttraining OG<br />Schönngasse 15-17/2/Top 3<br />1020 Wien<br />Österreich</address><p>Die Richtlinien der DSGVO können im Laufe der Zeit geändert werden. Wir werden unsere Datenschutzrichtlinien diesbezüglich immer wieder anpassen.</p><p>Falls Sie mit einem Aspekt unserer Datenschutzrichtlinie nicht einverstanden sind, stehen Ihnen Rechtsansprüche zu, die hier an entsprechender Stelle beschrieben sind. Diese Datenschutzrichtlinie gilt für Österreich und kann bezüglich anderer EU-Staaten abweichen.</p></section>
    <section><h2>2. Rechtmäßigkeit der Verarbeitung</h2><p>Die Einwilligung der Datenschutzerklärung gilt für die Verarbeitung personenbezogener Daten, die zur Erfüllung eines Vertrages, dessen Vertragspartei die betroffene Person ist, oder zur Durchführung vorvertraglicher Maßnahmen auf Antrag der betroffenen Person erforderlich ist, sowie zur Erfüllung rechtlicher Verpflichtungen und zur Wahrung der Rechte der betroffenen Person.</p></section>
    <section><h2>3. Arten der Verarbeitung</h2><h3>3.1 Kundendaten</h3><p>Um den Kontakt mit unseren Kunden und den reibungslosen Zahlungsverkehr aufrechtzuerhalten, werden Daten gespeichert. Diese personenbezogenen Daten werden über unsere Formulare auf www.viennaflight.at verarbeitet:</p><ul><li>Unternehmensdaten</li><li>Vor- und Nachname</li><li>Geburtsdatum</li><li>Adresse einschließlich Postleitzahl und Ortsangabe</li><li>Telefonnummer</li><li>E-Mail-Adresse</li><li>IP-Adresse</li></ul><h3>3.2 Besucher der Webseite</h3><p>Wir erfassen Daten unserer Besucher über die IP-Adresse und speichern den Namen der abgerufenen Datei, Datum und Uhrzeit des Abrufs, die übertragene Datenmenge, den Browsertyp, die Landesbezeichnung und anfragende URLs für interne statistische Zwecke. Andere personenbezogene Daten werden über den Besucher weder gespeichert noch verarbeitet.</p><h3>3.3 Daten von Verantwortlichen</h3><p>Wir erhalten laufend personenbezogene Daten von Verantwortlichen, die wir übernehmen und verarbeiten. Die Datenschutzeinwilligung und Richtigkeit der Daten ist beim Verantwortlichen zu beziehen. Ihnen stehen Rechtsansprüche zur Auskunftserteilung und Löschung Ihrer Daten seitens ViennaFlight, in diesem Punkt als Datenverarbeiter, zu.</p><p>Von Verantwortlichen, vorwiegend Event-Unternehmen, werden Vor- und Nachname, E-Mail-Adresse, Telefonnummer und Adresse übertragen.</p></section>
    <section><h2>4. Arten von Daten</h2><h3>4.1 Personenbezogene Daten</h3><p>Bis auf Widerruf verarbeiten wir Unternehmensdaten, Vor- und Nachname, Adresse einschließlich Postleitzahl und Ortsangabe, Telefonnummer und E-Mail-Adresse der betroffenen Person. Eine Weiterleitung an Dritte findet nur zum Zweck der Vertragsabwicklung statt, insbesondere zur Weitergabe von Bestelldaten an Lieferanten, soweit dies zu Abrechnungszwecken erforderlich ist oder Sie zuvor beim jeweiligen Verantwortlichen eingewilligt haben.</p><h3>4.1.1 Umgang mit Daten von Kindern</h3><p>Grundsätzlich speichert oder verarbeitet ViennaFlight keine personenbezogenen Daten von Kindern. Sollten diesbezügliche personenbezogene Daten verfügbar sein, dann nur unter Einwilligung der Obsorgeberechtigten. Für die ordnungsgemäße Buchung unserer Dienstleistungen ist die Altersbegrenzung von 16 Jahren einzuhalten.</p><h3>4.1.2 Weiterleitung an Dritte</h3><p>Um das breite Spektrum unserer Dienstleistungen gewährleisten zu können, leiten wir personenbezogene Daten zur Verarbeitung an unsere Partner weiter. Detaillierte Informationen erhalten Sie im Rahmen Ihres Auskunftsrechts.</p><h3>4.2 Sensible Daten</h3><p>ViennaFlight speichert und verarbeitet keine sensiblen Daten.</p></section>
    <section><h2>5. Auskunftsrecht</h2><p>Sie haben jederzeit das Recht auf Auskunft über Ihre von uns gespeicherten personenbezogenen Daten. ViennaFlight unterliegt als Verantwortlicher der Auskunftspflicht laut DSGVO.</p><p>ViennaFlight behält sich das Recht vor, die gewünschten Daten innerhalb einer Frist von einem Monat bereitzustellen, sofern Daten über die Person vorhanden sind. Der Antragsteller hat bei begründetem Zweifel gemäß DSGVO die Pflicht, seine Identität nachzuweisen.</p><h3>5.1 Richtigkeit der Daten</h3><p>Sollten die gespeicherten personenbezogenen Daten nicht richtig sein, hat ViennaFlight das Recht, diese Daten innerhalb einer Frist von einem Monat richtigzustellen.</p></section>
    <section><h2>6. Recht auf Löschung</h2><p>Sie haben den Rechtsanspruch, die von ViennaFlight gespeicherten Daten löschen zu lassen.</p><p>Sofern Sie dies beantragen, behält sich ViennaFlight das Recht vor, den Löschungsprozess innerhalb einer Frist von einem Monat abzuschließen. Nach der ordnungsgemäß durchgeführten Löschung wird eine Auskunft über die Daten vorgelegt. Falls Daten bei verarbeitenden Parteien vorhanden sind, behält sich ViennaFlight das Recht vor, die Frist um zwei Monate zu verlängern. Für die Dauer der Speicherung gelten interne Unternehmensrichtlinien.</p></section>
    <section><h2>7. Widerrufsrecht</h2><p>Ihr Widerrufsrecht finden Sie, sofern nicht anders angeführt, auf unserer Webseite unter Widerruf.</p></section>
    <section><h2>8. Sicherheit</h2><p>Die Webseite www.viennaflight.at ist durch ein geprüftes SSL-Zertifikat geschützt. Sicherungen des Systems werden regelmäßig durch unseren IT-Dienstleister durchgeführt.</p></section>
    <section><h2>9. Cookies</h2><p>Ein Cookie ist eine Information, die auf der Festplatte Ihres Computers gespeichert wird und Ihre Navigation auf einer Website aufzeichnet. So können Ihnen auf Grundlage der Informationen, die über Ihren letzten Besuch gespeichert wurden, maßgeschneiderte Optionen angeboten werden. Cookies können auch zur Analyse von Datenverkehr und zu Werbe- und Marketingzwecken genutzt werden.</p></section>
    <section><h2>10. Google Analytics</h2><p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Ireland Limited. Wenn der Verantwortliche für die Datenverarbeitung auf dieser Website außerhalb des Europäischen Wirtschaftsraumes oder der Schweiz sitzt, erfolgt die Google-Analytics-Datenverarbeitung durch Google LLC. Google LLC und Google Ireland Limited werden nachfolgend Google genannt.</p><p>Google Analytics verwendet Cookies, also Textdateien, die auf dem Computer des Seitenbesuchers gespeichert werden und eine Analyse der Benutzung der Website ermöglichen. Die durch das Cookie erzeugten Informationen über die Benutzung dieser Website, einschließlich der gekürzten IP-Adresse, werden in der Regel an einen Server von Google übertragen und dort gespeichert.</p><p>Google Analytics wird ausschließlich mit der Erweiterung _anonymizeIp() verwendet. Diese Erweiterung stellt eine Anonymisierung der IP-Adresse durch Kürzung sicher und schließt eine direkte Personenbeziehbarkeit aus. Die IP-Adresse wird innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Europäischen Wirtschaftsraumes zuvor gekürzt.</p><p>Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Die vom Browser im Rahmen von Google Analytics übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt.</p><p>Im Auftrag des Seitenbetreibers wird Google die anfallenden Informationen benutzen, um die Nutzung der Website auszuwerten, Berichte über Websiteaktivitäten zusammenzustellen und weitere mit der Website- und Internetnutzung verbundene Dienstleistungen gegenüber dem Seitenbetreiber zu erbringen. Das berechtigte Interesse an der Datenverarbeitung liegt in der Optimierung dieser Website, der Analyse ihrer Benutzung und der Anpassung der Inhalte. Die Interessen der Nutzer werden durch die Pseudonymisierung gewahrt.</p><p>Die Erfassung durch Google Analytics kann verhindert werden, indem der Seitenbesucher die Cookie-Einstellungen dieser Website anpasst. Der Erfassung und Speicherung der IP-Adresse sowie der durch Cookies erzeugten Daten kann jederzeit mit Wirkung für die Zukunft widersprochen werden. Das entsprechende Browser-Plug-in ist unter <a href="https://tools.google.com/dlpage/gaoptout">tools.google.com/dlpage/gaoptout</a> verfügbar.</p><p>Weitere Informationen zur Datennutzung durch Google und zu Widerspruchsmöglichkeiten finden Sie in der <a href="https://policies.google.com/privacy">Datenschutzerklärung von Google</a> und in den <a href="https://adssettings.google.com/authenticated">Einstellungen für Werbeeinblendungen</a>.</p></section>
    <section><h2>Verantwortlicher und Aufsichtsbehörde</h2><address><strong>ViennaFlight</strong><br />Flightsimulation &amp; Flighttraining OG<br />Schönngasse 15-17/2/Top 3<br />1020 Wien<br />Österreich</address><p>Rechtssystem: Österreich</p><h3>Kontaktdaten der lokalen Aufsichtsbehörde</h3><address>Österreichische Datenschutzbehörde<br />Wickenburggasse 8<br />1080 Wien<br />Telefon: <a href="tel:+431521520">+43 1 52 152-0</a></address><h3>Verantwortlich für die Datenschutzerklärung</h3><p>innovative desire e.U.<br />Prof. Ing. Yun Xiang, geprüfter Datenschutzexperte</p></section>
  </LegalPage>;
}
