"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AdminNavigation } from "../../components/AdminNavigation";
import type { AdminIdentity } from "../../lib/admin-auth";
import { formatDateNumeric, formatDateTimeInput, parseDateTimeInput } from "../../lib/date-format";
import type { DiscountType, VoucherRecord } from "../../lib/vouchers-db";

type Editor = { id?:number; code:string; description:string; discountType:DiscountType; discountValue:string; active:boolean; allowedEmail:string; maxUses:string; maxUsesPerEmail:string; startsAt:string; endsAt:string };
const emptyEditor:Editor={code:"",description:"",discountType:"percentage",discountValue:"",active:true,allowedEmail:"",maxUses:"",maxUsesPerEmail:"",startsAt:"",endsAt:""};

export default function VouchersAdminPage(){
  const router=useRouter(),[checking,setChecking]=useState(true),[identity,setIdentity]=useState<AdminIdentity|null>(null),[vouchers,setVouchers]=useState<VoucherRecord[]>([]),[editor,setEditor]=useState<Editor>(emptyEditor),[modalOpen,setModalOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[emailFilter,setEmailFilter]=useState("");
  const visibleVouchers=useMemo(()=>{const query=emailFilter.trim().toLowerCase();return query?vouchers.filter(voucher=>(voucher.allowed_email??"").toLowerCase().includes(query)||(voucher.redemption_emails??"").toLowerCase().split(",").some(email=>email.includes(query))):vouchers;},[emailFilter,vouchers]);
  const loadVouchers=useCallback(async()=>{const response=await fetch("/api/admin/vouchers",{credentials:"same-origin",cache:"no-store"});if(response.status===401){router.replace("/admin");return;}const data=await response.json();if(response.ok)setVouchers(data.vouchers);else setError(data.error??"Gutscheine konnten nicht geladen werden.");},[router]);
  useEffect(()=>{fetch("/api/admin/session",{credentials:"same-origin"}).then(response=>response.json()).then(data=>{if(!data.authenticated){router.replace("/admin");return;}setIdentity(data.user);void loadVouchers();}).catch(()=>setError("Die Sitzung konnte nicht geprüft werden.")).finally(()=>setChecking(false));},[loadVouchers,router]);
  useEffect(()=>{if(!identity)return;const interval=window.setInterval(()=>{if(document.visibilityState==="visible")void loadVouchers();},10_000);return()=>window.clearInterval(interval);},[identity,loadVouchers]);
  function create(){setEditor(emptyEditor);setModalOpen(true);setError("");setNotice("");}
  function edit(voucher:VoucherRecord){setEditor({id:voucher.id,code:voucher.code,description:voucher.description,discountType:voucher.discount_type,discountValue:String(voucher.discount_type==="fixed"?voucher.discount_value/100:voucher.discount_value),active:voucher.active===1,allowedEmail:voucher.allowed_email??"",maxUses:voucher.max_uses?.toString()??"",maxUsesPerEmail:voucher.max_uses_per_email?.toString()??"",startsAt:formatDateTimeInput(voucher.starts_at),endsAt:formatDateTimeInput(voucher.ends_at)});setModalOpen(true);setError("");setNotice("");}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");setNotice("");const payload={...editor,startsAt:parseDateTimeInput(editor.startsAt),endsAt:parseDateTimeInput(editor.endsAt)},response=await fetch("/api/admin/vouchers",{method:editor.id?"PATCH":"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),data=await response.json();if(response.ok){setNotice(editor.id?"Gutscheincode wurde aktualisiert.":"Gutscheincode wurde angelegt.");setEditor(emptyEditor);setModalOpen(false);await loadVouchers();}else setError(data.error??"Gutscheincode konnte nicht gespeichert werden.");setSaving(false);}
  async function toggle(voucher:VoucherRecord){const response=await fetch("/api/admin/vouchers",{method:"PATCH",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify({id:voucher.id,code:voucher.code,description:voucher.description,discountType:voucher.discount_type,discountValue:voucher.discount_type==="fixed"?voucher.discount_value/100:voucher.discount_value,active:voucher.active!==1,allowedEmail:voucher.allowed_email,maxUses:voucher.max_uses,maxUsesPerEmail:voucher.max_uses_per_email,startsAt:voucher.starts_at,endsAt:voucher.ends_at})}),data=await response.json();if(response.ok){setNotice(voucher.active?"Gutscheincode wurde deaktiviert.":"Gutscheincode wurde aktiviert.");await loadVouchers();}else setError(data.error??"Status konnte nicht geändert werden.");}
  async function remove(voucher:VoucherRecord){if(!window.confirm(`Gutscheincode „${voucher.code}“ endgültig löschen?`))return;const response=await fetch(`/api/admin/vouchers?id=${voucher.id}`,{method:"DELETE",credentials:"same-origin"}),data=await response.json();if(response.ok){setNotice("Gutscheincode wurde gelöscht.");await loadVouchers();}else setError(data.error??"Gutscheincode konnte nicht gelöscht werden.");}
  if(checking)return <main className="admin-loading"><span className="admin-spinner"/><p>Sitzung wird geprüft</p></main>;
  if(!identity)return <main className="admin-loading"><p>Weiterleitung zur Anmeldung</p></main>;
  return <main className="admin-shell"><AdminNavigation active="vouchers"/><section className="admin-content management-content">
    <header className="admin-topbar users-topbar"><div><span className="micro-label">Voucher Control</span><h1>Gutscheincodes</h1><p>Alle Codes, Einlösungen und Einschränkungen im Überblick.</p></div><button className="add-member-button" type="button" onClick={create} aria-label="Gutscheincode anlegen">+</button></header>
    {error&&<div className="admin-error" role="alert">{error}</div>}{notice&&<div className="admin-notice" role="status">{notice}</div>}
    <div className="voucher-metrics"><article><span>Codes gesamt</span><strong>{vouchers.length}</strong></article><article><span>Aktiv</span><strong>{vouchers.filter(voucher=>voucher.active===1).length}</strong></article><article><span>Einlösungen</span><strong>{vouchers.reduce((sum,voucher)=>sum+Number(voucher.redemption_count??0),0)}</strong></article></div>
    <section className="active-news-directory voucher-directory"><header><div><span className="micro-label">Übersicht</span><h2>Alle Gutscheincodes</h2></div><span>{visibleVouchers.length} von {vouchers.length}</span></header><div className="voucher-directory-filter"><label className="voucher-email-filter"><span>⌕</span><input type="search" value={emailFilter} onChange={event=>setEmailFilter(event.target.value)} placeholder="Nach E-Mail-Adresse filtern" aria-label="Gutscheincodes nach E-Mail-Adresse filtern"/>{emailFilter&&<button type="button" onClick={()=>setEmailFilter("")} aria-label="Filter löschen">×</button>}</label></div>
      {vouchers.length===0?<div className="management-empty"><span>◇</span><h3>Noch keine Gutscheincodes</h3><p>Mit dem Plus oben rechts können Sie einen Code anlegen.</p></div>:visibleVouchers.length===0?<div className="management-empty"><span>⌕</span><h3>Keine Treffer</h3><p>Zu dieser E-Mail-Adresse wurde kein Gutscheincode gefunden.</p></div>:<div className="voucher-directory-grid">{visibleVouchers.map(voucher=><article className={`voucher-card${voucher.active?"":" inactive"}`} key={voucher.id}><div className="voucher-card-main"><div><code>{voucher.code}</code><span className={`user-state ${voucher.active?"active":"disabled"}`}>{voucher.active?"Aktiv":"Deaktiviert"}</span></div><h3>{voucher.discount_type==="percentage"?`${voucher.discount_value}% Rabatt`:`€ ${(voucher.discount_value/100).toFixed(2)} Rabatt`}</h3><p>{voucher.description||"Keine interne Beschreibung"}</p></div><dl><div><dt>Verwendet</dt><dd>{voucher.redemption_count??0}{voucher.max_uses?` / ${voucher.max_uses}`:" / ∞"}</dd></div><div><dt>Je E-Mail</dt><dd>{voucher.max_uses_per_email??"∞"}</dd></div><div><dt>E-Mail-Bindung</dt><dd>{voucher.allowed_email??"Alle"}</dd></div><div><dt>Laufzeit</dt><dd>{voucher.starts_at?formatDateNumeric(voucher.starts_at):"Sofort"} bis {voucher.ends_at?formatDateNumeric(voucher.ends_at):"offen"}</dd></div></dl>{voucher.redemption_emails&&<div className="voucher-used-by"><span>Eingelöst von</span><p>{voucher.redemption_emails.split(",").join(", ")}</p></div>}<div className="voucher-actions"><button type="button" onClick={()=>edit(voucher)}>Bearbeiten</button><button type="button" onClick={()=>void toggle(voucher)}>{voucher.active?"Deaktivieren":"Aktivieren"}</button><button className="danger-button" type="button" onClick={()=>void remove(voucher)}>Löschen</button></div></article>)}</div>}
    </section>
    {modalOpen&&<div className="member-modal-backdrop"><form className="member-modal voucher-editor-modal" onSubmit={save}><header><div><span className="micro-label">{editor.id?"Code bearbeiten":"Neuer Code"}</span><h2>{editor.id?"Gutschein aktualisieren":"Gutschein anlegen"}</h2></div><button type="button" onClick={()=>setModalOpen(false)} aria-label="Schließen">×</button></header>
      <div className="management-row"><label>Gutscheincode<input required minLength={3} maxLength={40} pattern="[A-Za-z0-9_-]+" value={editor.code} onChange={event=>setEditor({...editor,code:event.target.value.toUpperCase()})} placeholder="VIENNA20"/></label><label>Status<select value={editor.active?"active":"inactive"} onChange={event=>setEditor({...editor,active:event.target.value==="active"})}><option value="active">Aktiv</option><option value="inactive">Deaktiviert</option></select></label></div>
      <label>Interne Beschreibung <span className="field-optional">optional</span><input maxLength={240} value={editor.description} onChange={event=>setEditor({...editor,description:event.target.value})} placeholder="Zum Beispiel Sommeraktion 2026"/></label>
      <div className="management-row"><label>Rabattart<select value={editor.discountType} onChange={event=>setEditor({...editor,discountType:event.target.value as DiscountType})}><option value="percentage">Prozent</option><option value="fixed">Fixbetrag in Euro</option></select></label><label>Rabattwert<input required min={editor.discountType==="percentage"?1:"0.01"} max={editor.discountType==="percentage"?100:undefined} step={editor.discountType==="percentage"?1:"0.01"} type="number" value={editor.discountValue} onChange={event=>setEditor({...editor,discountValue:event.target.value})}/></label></div>
      <label>Nur für diese E-Mail-Adresse <span className="field-optional">optional</span><input type="email" value={editor.allowedEmail} onChange={event=>setEditor({...editor,allowedEmail:event.target.value})} placeholder="Leer lassen für alle Kunden"/></label>
      <div className="management-row"><label>Maximale Einlösungen gesamt <span className="field-optional">optional</span><input type="number" min="1" step="1" value={editor.maxUses} onChange={event=>setEditor({...editor,maxUses:event.target.value})} placeholder="Unbegrenzt"/></label><label>Maximal je E-Mail-Adresse <span className="field-optional">optional</span><input type="number" min="1" step="1" value={editor.maxUsesPerEmail} onChange={event=>setEditor({...editor,maxUsesPerEmail:event.target.value})} placeholder="Unbegrenzt"/></label></div>
      <div className="management-row"><label>Gültig ab <span className="field-optional">optional</span><input type="text" inputMode="numeric" pattern="\d{2}\.\d{2}\.\d{4} (?:[01]\d|2[0-3]):[0-5]\d" placeholder="TT.MM.JJJJ HH:MM" value={editor.startsAt} onChange={event=>setEditor({...editor,startsAt:event.target.value})}/></label><label>Gültig bis <span className="field-optional">optional</span><input type="text" inputMode="numeric" pattern="\d{2}\.\d{2}\.\d{4} (?:[01]\d|2[0-3]):[0-5]\d" placeholder="TT.MM.JJJJ HH:MM" value={editor.endsAt} onChange={event=>setEditor({...editor,endsAt:event.target.value})}/></label></div>
      <p>Ein Code wird nur akzeptiert, wenn Status, Laufzeit, E-Mail-Bindung und Nutzungslimits erfüllt sind.</p><button className="button primary" disabled={saving} type="submit">{saving?"Speichert ...":editor.id?"Änderungen speichern":"Gutscheincode anlegen"}</button>
    </form></div>}
  </section></main>;
}
